In [2]:
import numpy as np

## DataTypes and Attributes

In [38]:
# Numpy's main datatype in ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [40]:
a2=np.array([[1,2.0,3.3],
            [4,5,6.1]])
a3=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.1]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [14]:
#numero de dimensiones
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.1]])

In [20]:
#create a dataframe from numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.1

## 2. creating arrays 

In [3]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [4]:
sample_array.dtype

dtype('int32')

In [7]:
ones=np.ones((2,3))

In [8]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
ones.dtype

dtype('float64')

In [12]:
type(ones)

numpy.ndarray

In [13]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[2, 0, 2, 1, 8],
       [9, 1, 4, 5, 9],
       [7, 6, 8, 6, 1]])

In [16]:
random_array.size

15

In [17]:
random_array.shape

(3, 5)

In [20]:
random_array2=np.random.random((5,3))
random_array2

array([[0.88152422, 0.15735267, 0.62400573],
       [0.40993621, 0.03365675, 0.65992181],
       [0.22370065, 0.97066602, 0.60931346],
       [0.40003933, 0.02546702, 0.28058261],
       [0.14399595, 0.01790231, 0.1301881 ]])

In [21]:
random_array2.shape

(5, 3)

In [24]:
random_array3=np.random.rand(5,3)
random_array3

array([[0.4229194 , 0.89025482, 0.28106432],
       [0.33126997, 0.16603681, 0.99516674],
       [0.09480568, 0.14340141, 0.3560715 ],
       [0.81001101, 0.0037838 , 0.08439101],
       [0.35070757, 0.38561245, 0.9847241 ]])

In [33]:
# pseudo random numbers
np.random.seed(seed=0)
random_array4=np.random.randint(10,size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [34]:
random_array4.shape

(5, 3)

## 3. viewing arrays and matrices

In [36]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a1

array([1, 2, 3])

In [41]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.1]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a1[0]

1

In [44]:
a2[0]

array([1. , 2. , 3.3])

In [45]:
a3.shape

(2, 3, 3)

In [46]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [48]:
a4.shape

(2, 3, 4, 5)

In [49]:
a4.ndim

4

In [50]:
#  get the firts 4 numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

## 4. manipulating and comparing arrays

## arithmetic

In [51]:
a1

array([1, 2, 3])

In [53]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [54]:
a1+ones

array([2., 3., 4.])

In [55]:
a1-ones

array([0., 1., 2.])

In [56]:
a1*ones

array([1., 2., 3.])

In [59]:
a1

array([1, 2, 3])

In [60]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.1]])

In [57]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 18.3]])

In [61]:
# how can you reshape a2 to be compatible with a3?
#search: how to reshape numpy array 
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [62]:
a1/ones

array([1., 2., 3.])

In [65]:
# floor division removes the decimals
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [66]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.1]])

In [67]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 37.21]])

In [68]:
3.3*3.3

10.889999999999999

In [69]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 37.21]])

In [70]:
a1

array([1, 2, 3])

In [71]:
np.add(a1,ones)

array([2., 3., 4.])

In [72]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.1]])

In [73]:
a2%2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.1]])

### aggregation
Aggregation=performing the same operation on a number of things

In [74]:
listy=[1,2,3]

In [75]:
type(listy)

list

In [76]:
sum(listy)

6

In [77]:
a1

array([1, 2, 3])

In [78]:
type(a1)

numpy.ndarray

In [79]:
sum(a1)

6

In [80]:
np.sum(a1)

6

In [81]:
# create a massive numpy array
massive_array=np.random.random(100000)
massive_array.size

100000

In [82]:
massive_array[:100]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839,
       0.63892108, 0.89155444, 0.68005557, 0.44919774, 0.97857093,
       0.11620191, 0.7670237 , 0.41182014, 0.67543908, 0.24979628,
       0.31321833, 0.96541622, 0.58846509, 0.65966841, 0.53320625,
       0.23053302, 0.39486929, 0.61880856, 0.47486752, 0.47013219,
       0.71607453, 0.287991  , 0.38346223, 0.74916984, 0.87845219,
       0.10286336, 0.09237389, 0.35404666, 0.55181626, 0.03362509,
       0.96896177, 0.32099724, 0.22126269, 0.1412639 , 0.09725993,
       0.98404224, 0.26034093, 0.53702252, 0.44792617, 0.09956909,
       0.35231166, 0.46924917, 0.84114013, 0.90464774, 0.03755938,
       0.50831545, 0.16684751, 0.77905102, 0.8649333 , 0.41139672,
       0.13997259, 0.03322239, 0.98257496, 0.37329075, 0.42007537,
       0.05058812, 0.36549611, 0.01662797, 0.23074234, 0.7649117 ,
       0.94412352, 0.74999925, 0.33940382, 0.48954894, 0.33898

In [83]:
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [84]:
%timeit sum(massive_array) #python sum()
%timeit np.sum(massive_array) #NumPy's sum()

The slowest run took 6.32 times longer than the fastest. This could mean that an intermediate result is being cached.
29.4 ms ± 23.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
73.1 µs ± 17.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [86]:
 a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.1]])

In [87]:
np.mean(a2)

3.5666666666666664

In [89]:
np.max(a2)

6.1

In [90]:
np.min(a2)

1.0

In [91]:
np.std(a2)

1.7211107524567448

In [92]:
np.var(a2)

2.962222222222222

In [93]:
#standar deviation= squareroot of variance
np.sqrt(np.var(a))